# This file is a template, and might need editing before it works on your project.
# Read more about this script on this blog post https://about.gitlab.com/2018/10/24/setting-up-gitlab-ci-for-android-projects/, by Jason Lenny
# If you are interested in using Android with FastLane for publishing take a look at the Android-Fastlane template.

stages:
  - build
  - deployontarget
  - cleanupcache

imageBuild:
  stage: build
  only:
   - develop
  script:
    - ssh -P root@192.168.200.141 "cd /opt/ai-services/$CI_PROJECT_NAME && 
                                   git pull && git checkout develop && cd .. && 
                                   docker-compose build --no-cache $CI_PROJECT_NAME"

deployOnTarget:
  stage: deployontarget
  only:
   - develop
  script:
    - ssh -P root@192.168.200.141 "cd /opt/ai-services/ && docker-compose up -d $CI_PROJECT_NAME"

cleanupCache:
  stage: cleanupcache
  only:
   - develop
  script:
    - ssh -P root@192.168.200.141 "docker system prune -f"
